# Generated by Django 2.1.7 on 2020-02-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200116_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
